### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by waxilu** [ItsAML/X-Ui-to-Marzban#3]
Enter (a/m) to Continue:

after this step Its crash and not work

**Comment by ItsAML** [comment]
سلام اروری که دریافت کردین رو بفرستید، ولی احتمال میدم ارور NoneType باشه و صرفا در مواقعی رخ میده که از پنل x-ui یوزر هارو دریافت نکرده باشید، عملا وقتی یوزری برای مهاجرت دادن نیست و تلاش برای مهاجرت کنید این ارور رو بهتون برمیگردونه

برای راه حل های احتمالی:
نسخه x-ui رو اگه قدیمی هست اپدیت کنید
اگه از فورک خاصی مثل سنایی یا علیرضا استفاده میکنید داخل بخش متغیر ها مشخص کنید
اطلاعات پنل هارو دوباره چک کنید

**Comment by waxilu** [comment]
```
Traceback (most recent call last):
  File "/htdocs/X-Ui-to-Marzban-main/main.py", line 417, in <module>
    user_data = get_x_inbounds_with_uuid(X_SESSION)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/htdocs/X-Ui-to-Marzban-main/main.py", line 159, in get_x_inbounds_with_uuid
    for client, uuid in zip(client_stats, uuid_stats):
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

```
